p8105_hw2_bl3175
================

``` r
# 1) Import and clean pols data
pols <- read_csv("./data/pols-month.csv") |>
  separate(mon, into = c("year","month","day"), convert = TRUE) |>  # split YYYY-MM-DD
  mutate(
    month     = tolower(month.name[month]),   # number -> month name (lowercase)
    president = if_else(prez_gop == 1, "gop", "dem"),
    month_num = match(month, tolower(month.name))  # 1..12 for stable sorting
  ) |>
  select(year, month, month_num, president, starts_with("gov"), starts_with("sen"),
         -prez_dem, -prez_gop, -day) |>
  arrange(year, month_num) |>
  select(-month_num)

# 2) Import and clean snp data
snp <- read_csv("./data/snp.csv") |>
  separate(date, into = c("year","month","day"), convert = TRUE) |>
  mutate(
    month     = tolower(month.name[month]),
    month_num = match(month, tolower(month.name))
  ) |>
  select(year, month, month_num, close) |>
  arrange(year, month_num) |>
  select(-month_num)

# 3) Import and tidy unemployment data (wide -> long)
unemp <- read_csv("./data/unemployment.csv") |>
  pivot_longer(
    cols = -Year,
    names_to  = "month_abbr",
    values_to = "unemployment"
  ) |>
  mutate(
    month     = tolower(month.name[match(month_abbr, month.abb)]),
    month_num = match(month, tolower(month.name))
  ) |>
  rename(year = Year) |>   
  select(year, month, month_num, unemployment) |>
  arrange(year, month_num) |>
  select(-month_num)

# 4) Merge all datasets
p1_merged <- pols |>
  left_join(snp,  by = c("year","month")) |>
  left_join(unemp, by = c("year","month"))

# 5) Quick summary in output
dim(p1_merged)                         # dimensions
```

    ## [1] 822   9

``` r
range(p1_merged$year, na.rm = TRUE)    # year range
```

    ## [1] 1947 2015

``` r
names(p1_merged)                       # variable names
```

    ## [1] "year"         "month"        "president"    "gov_gop"      "gov_dem"     
    ## [6] "sen_gop"      "sen_dem"      "close"        "unemployment"

``` r
head(p1_merged, 5)                     # peek first rows
```

    ## # A tibble: 5 × 9
    ##    year month    president gov_gop gov_dem sen_gop sen_dem close unemployment
    ##   <dbl> <chr>    <chr>       <dbl>   <dbl>   <dbl>   <dbl> <dbl>        <dbl>
    ## 1  1947 january  dem            23      23      51      45    NA           NA
    ## 2  1947 february dem            23      23      51      45    NA           NA
    ## 3  1947 march    dem            23      23      51      45    NA           NA
    ## 4  1947 april    dem            23      23      51      45    NA           NA
    ## 5  1947 may      dem            23      23      51      45    NA           NA

The merged dataset has 822 rows and 9 columns, covering years 1947–2015.
Key variables include the month label (month), the party of the sitting
president (president), the S&P 500 closing level (close), and the
unemployment rate (unemployment). Column names are: year, month,
president, gov_gop, gov_dem, sen_gop, sen_dem, close, unemployment.

``` r
# --- helpers to standardize column names across sheets -----------------
# ensure there is a 'sports' integer column
std_sports <- function(df) {
  if ("sports" %in% names(df)) {
    df |> dplyr::mutate(sports = as.integer(round(sports)))
  } else if ("sports_balls" %in% names(df)) {
    df |> dplyr::rename(sports = sports_balls) |>
      dplyr::mutate(sports = as.integer(round(sports)))
  } else {
    df |> dplyr::mutate(sports = NA_integer_)
  }
}

# ensure 'weight_tons' exists
std_weight <- function(df) {
  if ("weight_tons" %in% names(df)) df
  else if ("weight" %in% names(df)) dplyr::rename(df, weight_tons = weight)
  else df
}

# ensure 'cigarette_butts' exists
std_cigs <- function(df) {
  if ("cigarette_butts" %in% names(df)) df
  else if ("cigarette" %in% names(df)) dplyr::rename(df, cigarette_butts = cigarette)
  else df |> dplyr::mutate(cigarette_butts = NA_real_)
}

# read one sheet and clean
read_trash <- function(sheet_name, wheel_label) {
  readxl::read_excel("./data/202409 Trash Wheel Collection Data.xlsx",
                     sheet = sheet_name, skip = 1) |>
    janitor::clean_names() |>                  # snake_case names
    dplyr::filter(!is.na(dumpster)) |>         # drop non-data rows
    dplyr::mutate(year = as.integer(year)) |>  # <<< make 'year' consistent
    std_weight() |> std_cigs() |> std_sports() |>
    dplyr::mutate(wheel = wheel_label,
                  month = stringr::str_to_title(month))  # e.g., "June"
}

# read three wheels
mr   <- read_trash("Mr. Trash Wheel",         "Mr")
prof <- read_trash("Professor Trash Wheel",   "Professor")
gw   <- read_trash("Gwynnda Trash Wheel",     "Gwynnda")

# combine
trash <- dplyr::bind_rows(mr, prof, gw)

# summaries required by the prompt
prof_total_weight <- trash |>
  dplyr::filter(wheel == "Professor") |>
  dplyr::summarise(total_weight_tons = sum(weight_tons, na.rm = TRUE))

gw_cig_2022_06 <- trash |>
  dplyr::filter(wheel == "Gwynnda", year == 2022, month == "June") |>
  dplyr::summarise(total_cig_butts = sum(cigarette_butts, na.rm = TRUE))

# counts for inline R if needed
n_obs_trash <- nrow(trash)
vars_trash  <- names(trash)

# quick peek
head(trash, 5)
```

    ## # A tibble: 5 × 17
    ##   dumpster month  year date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ## 1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ## 2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ## 3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ## 4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ## 5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ## # ℹ 11 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports <int>, homes_powered <dbl>, x15 <lgl>, x16 <lgl>,
    ## #   wheel <chr>

``` r
prof_total_weight
```

    ## # A tibble: 1 × 1
    ##   total_weight_tons
    ##               <dbl>
    ## 1              247.

``` r
gw_cig_2022_06
```

    ## # A tibble: 1 × 1
    ##   total_cig_butts
    ##             <dbl>
    ## 1           18120

The combined Trash Wheel dataset has 1033 rows, including variables such
as dumpster, month, year, weight_tons, and cigarette_butts. For
available data, Professor Trash Wheel collected 246.74 tons in total.
Gwynnda collected 1.812^{4} cigarette butts in June 2022.

``` r
# --- Problem 3: NYC ZORI data ------------------------------------------

# clean ZIP metadata
zip_meta <- read_csv("./data/Zip Codes.csv", show_col_types = FALSE) |>
  clean_names() |>
  select(
    county = county,
    zip    = matches("^zip"),
    neighborhood = neighborhood
  ) |>
  mutate(
    county = str_trim(county),
    borough = case_match(
      county,
      "Bronx" ~ "Bronx",
      "Kings" ~ "Brooklyn",
      "New York" ~ "Manhattan",
      "Queens" ~ "Queens",
      "Richmond" ~ "Staten Island",
      .default = county
    ),
    zip = as.character(zip)
  ) |>
  select(borough, neighborhood, zip)

# clean Zillow ZORI
zori_raw <- read_csv("./data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv",
                     show_col_types = FALSE) |>
  clean_names()

meta_cols <- c("region_id","size_rank","region_name","region_type",
               "state_name","state","city","metro","county_name")

zori_tidy <- zori_raw |>
  filter(region_type == "zip", state_name == "NY") |>
  pivot_longer(
    cols = -all_of(meta_cols),
    names_to   = "ymd_str",
    values_to  = "zori"
  ) |>
  mutate(
    ymd_str = str_remove(ymd_str, "^x"),
    date    = ymd(str_replace_all(ymd_str, "_", "-"), quiet = TRUE),
    ym      = floor_date(date, "month"),
    zip     = as.character(region_name),
    borough = case_match(
      county_name,
      "Bronx County" ~ "Bronx",
      "Kings County" ~ "Brooklyn",
      "New York County" ~ "Manhattan",
      "Queens County" ~ "Queens",
      "Richmond County" ~ "Staten Island",
      .default = county_name
    )
  ) |>
  select(zip, borough, ym, zori)

# merge ZORI with metadata
zori_final <- zori_tidy |>
  left_join(select(zip_meta, zip, borough_meta = borough, neighborhood),
            by = "zip") |>
  mutate(borough = coalesce(borough, borough_meta)) |>
  select(zip, borough, neighborhood, ym, zori)

# summary numbers
n_obs_p3   <- nrow(zori_final)
n_zip_p3   <- n_distinct(zori_final$zip)
n_neigh_p3 <- n_distinct(na.omit(zori_final$neighborhood))

# ZIP codes missing in Zillow
zips_only_in_meta <- setdiff(zip_meta$zip, unique(zori_final$zip))

# changes from 2020 to 2021
zori_2020_01 <- zori_final |>
  filter(ym == ymd("2020-01-01")) |>
  select(zip, zori_2020_01 = zori)

zori_2021_01 <- zori_final |>
  filter(ym == ymd("2021-01-01")) |>
  select(zip, zori_2021_01 = zori)

drops_tbl <- zori_2020_01 |>
  inner_join(zori_2021_01, by = "zip") |>
  mutate(drop = zori_2021_01 - zori_2020_01) |>
  left_join(distinct(zori_final, zip, borough, neighborhood), by = "zip") |>
  arrange(drop) |>
  slice_head(n = 10) |>
  select(zip, borough, neighborhood, zori_2020_01, zori_2021_01, drop)
head(zori_final, 5)
```

    ## # A tibble: 5 × 5
    ##   zip   borough neighborhood ym          zori
    ##   <chr> <chr>   <chr>        <date>     <dbl>
    ## 1 11368 Queens  West Queens  2015-01-01    NA
    ## 2 11368 Queens  West Queens  2015-02-01    NA
    ## 3 11368 Queens  West Queens  2015-03-01    NA
    ## 4 11368 Queens  West Queens  2015-04-01    NA
    ## 5 11368 Queens  West Queens  2015-05-01    NA

``` r
tibble::tibble(zips_only_in_meta = head(zips_only_in_meta, 10))
```

    ## # A tibble: 10 × 1
    ##    zips_only_in_meta
    ##    <chr>            
    ##  1 10464            
    ##  2 10474            
    ##  3 10475            
    ##  4 10499            
    ##  5 10550            
    ##  6 10704            
    ##  7 10705            
    ##  8 10803            
    ##  9 11202            
    ## 10 11224

``` r
drops_tbl
```

    ## # A tibble: 10 × 6
    ##    zip   borough   neighborhood                  zori_2020_01 zori_2021_01  drop
    ##    <chr> <chr>     <chr>                                <dbl>        <dbl> <dbl>
    ##  1 10007 Manhattan Lower Manhattan                      6334.        5422. -913.
    ##  2 10069 Manhattan <NA>                                 4623.        3875. -748.
    ##  3 10009 Manhattan Lower East Side                      3406.        2692. -714.
    ##  4 10016 Manhattan Gramercy Park and Murray Hill        3731.        3019. -712.
    ##  5 10001 Manhattan Chelsea and Clinton                  4108.        3398. -710.
    ##  6 10002 Manhattan Lower East Side                      3645.        2935. -710.
    ##  7 10004 Manhattan Lower Manhattan                      3150.        2444. -706.
    ##  8 10038 Manhattan Lower Manhattan                      3573.        2876. -698.
    ##  9 10012 Manhattan Greenwich Village and Soho           3629.        2942. -686.
    ## 10 10010 Manhattan Gramercy Park and Murray Hill        3697.        3012. -685.

The tidy NYC ZORI dataset has 17516 rows, covering 149 unique ZIP codes
and 42 unique neighborhoods. There are 171 ZIP codes present in the ZIP
metadata but not in the Zillow dataset (e.g., 10464, 10474, 10475).
Comparing January 2020 to January 2021, the largest drop occurs at ZIP
10007 in Manhattan, with neighborhood Lower Manhattan, changing from
6334.2106678 to 5421.614077, a difference of -912.5965909.
